
Vagrant.configure('2') do |config|
  # "vmware_desktop" should be the only one needed here.
  # https://github.com/hashicorp/vagrant/issues/4188#issuecomment-158239234
  ["vmware_desktop", "vmware_fusion", "vmware_workstation"].each do |confusing|
    config.vm.provider confusing do |box|
      box.gui = true
    end
  end
end